workflows:
  version: 2
  build-deploy:
    jobs:
      - build
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Do work
          command: |
            echo "I'm on a remote docker"
