workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - build2:
          requires:
            - build


version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Sleep!
          command: |
            sleep 120
  build2:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Sleep!
          command: |
            echo "sleeping for 8 hours"
            sleep 28800
